language: java

sudo: false

jdk: oraclejdk8

script: mvn clean verify

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - secure: bbA/HbJxzHw9MAGFP326uz+RuOoSoug8sBmKXZ6MFo65xfQsDmIVpIFFdRCEQcpN5hWZMECrRxD+KkdBLE/qfbNPfjN+y39AKjZaGjbPH0KHdb56Sd2s8okm0VhcXgugv3MjJX/kMqqf92JuIKg9UCaBYmDpBz1E2OlBHgZ6ueriKD+97yZYU926HgYZV3ry0bXzScw1P5ZDEsXfW6iRbJbUZpKy0XvT9fUSm6FgD6x3faLPk+4cv5FBlu6bkJeB7GmH+ZtPI4nWEx0XSB4J1HKsL0h+bjY2NQoLBgtQECJyyDzHAJV7l8PE40WfM3jaPuBxYKl2UkhsvFGxlkDG63Lg/IifSpIHN4OJKKi72+g6/rO6vxFG5WEkvpcqKJ2LUEnxmkRgD5xNpMWOEdbxgPBqJEK/NfZugRNLzG/xF86Gg8NWDMtyhDxOqCSEViqyGITMia9ff/vIOcgZfHXcYzDFGbKpMhlTlVP6jt8XpN/igS2jQt1LySkoAheDkMqwadkf4gqE1QH+QBCQCx9WPixSx6JdxaZIsvxop4xWv1P5AVzst27jKal/lRGowZpsX6TYnnzdYaO8pKtygeU+r5LQuNzyrUzqPVWoH6iimfN4TYw6pA6AT3azY6SgmCiz/TRxy/RWTnE51w1S27zTr5tvAJdRQlmopKKWouqc6UU=
  - secure: m1A2reS4GsXvP09y45YpvfF6jwx3TlkJ1MZCuQ8K3Uk1tIFtvssjItwKqCc7UImt/FyjO8fvUx9ItzHGC2UUrreHTYEohF7B6e8bwcU9Qvirim6xa5oLGqfqtcUjfOR3uD6AKGAw6yHStq2oJFM+qL3S3VZhZGkdbd0R5m6Tidu5nQEoU3T+NIM8z6G1pblvETuZ4NrQoMcU35jQvuAOGeBTPB2GDqpGVncQi3oMjpg8cjKI1cuoTxsHbMj8Wy2pURXQuP4/XhBFDmh49qjjjZ/qqqeey2PtGyD0GXuLM4CkGHzn3+VEYX5u+XlXM+IDcr76mfoDY3BVWjdG17rgM8r9uuriloJOUC0mboN+/lq0A2yeQyYjViv8OrZ4zNGwdF+mv1dGeIFEnNZRFprbfvJIvy058NnqSmMWneGOlZ+wmv28iPqvuRCTAujRUsOdZua9hO06zFNbiavKGHGgpMMl11avUJHI2h3dtEuiiG/fE+ZHz72MPemU7X/MxS1RsVGk3OMTfOiPYLrtnSvXxdULirQk4fLDmMRjOIr2gtzvE0YqYeuh4HdS1G6Vysenl65u5ew8VEHSxN6JvSRZkidsIdeudbN19jiii56M5pqR/pK88BJfYJjEQlzFqsmzrQ5jSIDjcGsSpx82k8PeuvSBqxS0eU+fRFM6+ATe68o=

after_success:
- bash <(curl -s https://codecov.io/bash)
- "[[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]] && mvn deploy -DskipTests --settings settings.xml"
