language: java

sudo: false

jdk: oraclejdk8

script: mvn clean verify

cache:
  directories:
  - "$HOME/.m2"

after_success:
- bash <(curl -s https://codecov.io/bash)
- "[[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]] && mvn deploy -DskipTests --settings settings.xml"
